stages:
  - test
  - release
#test:backend:python3.10:
#  stage: test
#  image: python:3.10
#  script:
#    - pip install .[develop]
#    - python -m pytest
#    - mypy tse

pages:
  stage: release
  image: python:3.10
  script:
    - pip install .[develop]
    - cd docs
    - make html
    - mv build/html ../public
  artifacts:
    paths:
      - public
#  only:
#    - tags

build:
  stage: release
  image: python:3.8
  script:
    - pip install .
    - pip install build
    - python -m build
    - cp dist/* build
    - export PACKAGE_VERSION=`python -m setup --version`
    - echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> build.env
  only:
    - tags
  artifacts:
    reports:
      dotenv: build.env
    paths:
      - build

packages:
  stage: release
  image: curlimages/curl:latest
  script:
  - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "build/tse.py-${PACKAGE_VERSION}.tar.gz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/tse.py/${PACKAGE_VERSION}/bnn-${PACKAGE_VERSION}.tar.gz"'
  - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "build/tse.py-${PACKAGE_VERSION}-py3-none-any.whl" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/tse.py/${PACKAGE_VERSION}/bnn-${PACKAGE_VERSION}-py3-none-any.whl"'
  artifacts:
    paths:
      - build
  only:
    - tags
  needs: ["build"]
